podman build -t=hal9000 .
podman run -e GH_WDF_USER=$GH_WDF_USER -e GH_WDF_TOKEN=$GH_WDF_TOKEN -e GH_TOOLS_USER=$GH_TOOLS_USER -e GH_TOOLS_TOKEN=$GH_TOOLS_TOKEN -e GH_COM_USER=$GH_COM_USER -e GH_COM_TOKEN=$GH_COM_TOKEN -p 3000:3000 hal9000
